name: mlproject
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - numpy
  - pandas
  - scikit-learn
  - scipy
  - matplotlib
  - jupyter
  - pip:
      - mlflow
      - pyyaml
      - dagshub
